export const siteConfig = {
  name: "Workout Forge",
  shortName: "Workout",
  creator: "Workout Forge Team",
  locale: "en_US",
  category: "health",
  tagline:
    "A dark-mode workout planner with training tracking, protected user pages, and a public exercise catalog.",
  description:
    "Workout Forge is a modern workout tracker built with Next.js, Better Auth, MongoDB, Mongoose, DaisyUI, and TanStack Query.",
  keywords: [
    "workout planner",
    "training log",
    "exercise catalog",
    "Next.js workout app",
    "DaisyUI dark mode",
    "MongoDB workouts",
    "Better Auth",
  ],
  nav: [
    { href: "/", label: "Home" },
    { href: "/workouts", label: "Workouts" },
    // { href: "/dashboard", label: "Dashboard" },
    // { href: "/settings", label: "Settings" },
    // { href: "/admin", label: "Admin" },
  ],
  footerLinks: [
    { href: "/", label: "Home" },
    { href: "/workouts", label: "Workouts" },
    { href: "/dashboard", label: "Dashboard" },
    { href: "/settings", label: "Settings" },
    { href: "/login", label: "Sign in" },
    { href: "/register", label: "Create account" },
  ],
  stack: [
    "Next.js 16",
    "Tailwind 4",
    "DaisyUI 5",
    "Lucide React",
    "Better Auth",
    "TanStack Query",
    "MongoDB",
    "Mongoose",
  ],
} as const;
